appliction/application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectMultipleField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    carbohydrates = IntegerField('Carbohydrates', validators=[DataRequired()], render_kw={"placeholder": "Carbohydrates"})
    lipids = IntegerField('Lipids', validators=[DataRequired()], render_kw={"placeholder": "Lipids"})
    proteins = IntegerField('Proteins', validators=[DataRequired()], render_kw={"placeholder": "Proteins"})
    calories = IntegerField('Calories', validators=[DataRequired()], render_kw={"placeholder": "Calories"})
    submit = SubmitField('Post')
    cuisine = SelectMultipleField('Select origin (one or several)', choices=[], coerce=int)
    category = SelectMultipleField('Select category (one or several)', choices=[], coerce=int)
    ingredient = SelectField('Select ingredient', choices=[])
    amount = IntegerField(validators=[DataRequired()], render_kw={"placeholder": "Amount"})


class SearchForm(FlaskForm):
    searched = StringField("Searched")
    submit = SubmitField('Search')

appliction/application/main/routes.py
from flask import render_template, request, Blueprint
from application.database import Post, Ingredient, Category, Cuisine
from application.posts.forms import SearchForm

main = Blueprint('main', __name__)


@main.context_processor
def navbar():
    form = SearchForm()
    return dict(form=form)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/ingredients")
def ingredients():
    page = request.args.get('page', 1, type=int)
    ingredients = Ingredient.query.order_by(Ingredient.name.asc()).paginate(page=page, per_page=10)
    return render_template('ingredients.html', ingredients=ingredients)


@main.route("/categories")
def categories():
    page = request.args.get('page', 1, type=int)
    categories = Category.query.order_by(Category.name).paginate(page=page, per_page=10)
    return render_template('categories.html', categories=categories)


@main.route("/cuisines")
def cuisines():
    page = request.args.get('page', 1, type=int)
    cuisines = Cuisine.query.order_by(Cuisine.name).paginate(page=page, per_page=10)
    return render_template('cuisines.html', cuisines=cuisines)


@main.route("/search", methods=['POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        searched = form.searched.data
        posts = Post.query.filter(Post.content.like('%' + searched + '%')).order_by(Post.title).all()
        return render_template('search.html', form=form, searched=searched, posts=posts)

appliction/application/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from application import db
from application.database import Post, Comment, Like, Cuisine, Category, Ingredient, post_ingredient_association
from application.posts.forms import PostForm, SearchForm
from no_orm import Database

posts = Blueprint('posts', __name__)


@posts.context_processor
def navbar():
    form = SearchForm()
    return dict(form=form)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    form.category.choices = [(ca.id, ca.name) for ca in Category.query.order_by(Category.name.asc()).all()]
    form.cuisine.choices = [(cu.id, cu.name) for cu in Cuisine.query.order_by(Cuisine.name.asc()).all()]
    form.ingredient.choices = [(i.id, i.name) for i in Ingredient.query.order_by(Ingredient.name.asc()).all()]
    if form.validate_on_submit():
        flash("Your post has been created!", 'success')
        post = Post(title=form.title.data, content=form.content.data, author=current_user, calories=form.calories.data,
                    lipids=form.lipids.data, carbohydrates=form.carbohydrates.data, proteins=form.proteins.data)

        categories = Category.query.filter(Category.id.in_(form.category.data)).all()
        cuisines = Cuisine.query.filter(Cuisine.id.in_(form.cuisine.data)).all()

        post.cuisines.extend(cuisines)
        post.categories.extend(categories)

        db.session.add(post)
        db.session.commit()

        for i in range(len(request.form.getlist('ingredient'))):
            ingredient_id = int(request.form.getlist('ingredient')[i])
            amount = int(request.form.getlist('amount')[i])

            post_ingredients = post_ingredient_association.insert().values(post_id=post.id, ingredient_id=ingredient_id, amount=amount)
            db.session.execute(post_ingredients)
            db.session.commit()

        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    cuisines = Cuisine.query.all()
    categories = Category.query.all()
    amount = Database.get_ingredients(post_id)
    return render_template('post.html', title=post.title, post=post, cuisines=cuisines, categories=categories, amount=amount)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and current_user.role != 'admin':
        abort(403)
    form = PostForm()
    form.category.choices = [(ca.id, ca.name) for ca in Category.query.order_by(Category.name.asc()).all()]
    form.cuisine.choices = [(cu.id, cu.name) for cu in Cuisine.query.order_by(Cuisine.name.asc()).all()]
    form.ingredient.choices = [(i.id, i.name) for i in Ingredient.query.order_by(Ingredient.name.asc()).all()]
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.calories = form.calories.data
        post.lipids = form.lipids.data
        post.carbohydrates = form.carbohydrates.data
        post.proteins = form.proteins.data

        post.cuisines = []
        post.ingredients = []
        post.categories = []

        categories = Category.query.filter(Category.id.in_(form.category.data)).all()
        cuisines = Cuisine.query.filter(Cuisine.id.in_(form.cuisine.data)).all()

        for i in range(len(request.form.getlist('ingredient'))):
            ingredient_id = int(request.form.getlist('ingredient')[i])
            amount = int(request.form.getlist('amount')[i])

            post_ingredients = post_ingredient_association.insert().values(post_id=post.id, ingredient_id=ingredient_id, amount=amount)
            db.session.execute(post_ingredients)
            db.session.commit()

        post.cuisines.extend(cuisines)
        post.categories.extend(categories)
        db.session.commit()
        flash("Your post has been updated!", 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.lipids.data = post.lipids
        form.calories.data = post.calories
        form.carbohydrates.data = post.carbohydrates
        form.proteins.data = post.proteins
        form.ingredient.data = post.ingredients
        form.cuisine.data = post.cuisines
        form.category.data = post.categories
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and current_user.role != 'admin':
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Post has been deleted!", 'info')
    return redirect(url_for('main.home'))


@posts.route("/create-comment/<int:post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')
    post = Post.query.get_or_404(post_id)
    if not text:
        flash("Comment can not be empty!", 'warning')
    else:
        comment = Comment(text=text, author=current_user, post_id=post_id)
        db.session.add(comment)
        db.session.commit()
        flash("Comment has been added successfully!", 'success')

    return redirect(url_for('posts.post', post_id=post.id))


@posts.route("/delete-comment/<int:comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.post.author and current_user.role != 'admin':
        abort(403)
    else:
        db.session.delete(comment)
        db.session.commit()
        flash("Comment has been deleted.", 'info')
    return redirect(url_for('main.home'))


@posts.route("/like-post/<int:post_id>", methods=['GET'])
@login_required
def like(post_id):
    post = Post.query.get_or_404(post_id)
    like = Like.query.filter_by(author=current_user, post_id=post_id).first()
    if like:
        db.session.delete(like)
    else:
        like = Like(author=current_user, post_id=post_id)
        flash("Post added to favourites", 'info')
        db.session.add(like)
    db.session.commit()

    return redirect(url_for('posts.post', post_id=post.id))


@posts.route("/cuisine/<int:cuisine_id>")
def dish_cuisine(cuisine_id):
    cuisine = Cuisine.query.get_or_404(cuisine_id)
    result = Database.get_cuisines(cuisine_id)
    return render_template('dish_cuisines.html', cuisine=cuisine, result=result)


@posts.route("/category/<int:category_id>")
def dish_category(category_id):
    category = Category.query.get_or_404(category_id)
    result = Database.get_categories(category_id)
    return render_template('dish_categories.html', result=result, category=category)

appliction/application/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from application import db, bcrypt
from application.database import Users, Post, Like
from application.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from application.users.utils import save_picture, send_reset_email
from application.posts.forms import SearchForm
from no_orm import Database
from datetime import datetime

users = Blueprint('users', __name__)


@users.context_processor
def navbar():
    form = SearchForm()
    return dict(form=form)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        '''
        # no orm start
        id = None
        username = form.username.data
        email = form.email.data
        password = form.password.data
        reg_date = datetime.now()
        if form.email.data in ['sasukeutiha719@gmail.com', 'kazakevitchtatjana@yandex.ru', 'Sakura_6@mail.ru', 'Sasukeutiha719@gmail.com', 'Kazakevitchtatjana@yandex.ru', 'sakura_6@mail.ru', 'chefblog9@gmail.com', 'Chefblog9@gmail.com']:
            role = 'admin'
        else:
            role = 'user'
        bio = 'Not set yet'
        new_user = Database(id, username, email, password, reg_date, role, bio)
        new_user.save()
        # no orm end
        '''
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        if form.email.data in ['sasukeutiha719@gmail.com', 'kazakevitchtatjana@yandex.ru', 'Sakura_6@mail.ru', 'Sasukeutiha719@gmail.com', 'Kazakevitchtatjana@yandex.ru', 'sakura_6@mail.ru', 'chefblog9@gmail.com', 'Chefblog9@gmail.com']:
            role = 'admin'
        else:
            role = 'user'
        user = Users(username=form.username.data, email=form.email.data, password=hashed_password, role=role)
        db.session.add(user)
        db.session.commit()
        flash('Yor account has been created successfully. Now you are able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        '''
        # no orm start
        user = Database.get_by_email(form.email.data)

        if user:
            login_user(user, remember=form.remember.data)
            flash("You have logged in", 'success')
        else:
            flash("Wrong password", 'danger')
        # no orm end
        '''
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f"Welcome, {user.username}!", 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login is unsuccessful. Please check your password and email.', 'danger')
    return render_template('login.html', title='Log In', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash("Your account has been updated!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = Users.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email with instructions has been sent.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Yor password has been reset successfully!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/user/favourites")
@login_required
def favourite():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.join(Like, (Like.post_id == Post.id)).filter(Like.user_id == current_user.id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('favourite_posts.html', posts=posts, user=current_user)

appliction/application/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
    <p>This is an "About" page</p>
{% endblock content %}

appliction/application/templates/categories.html
{% extends "layout.html" %}
{% block content %}
    {% for category in categories.items %}
        <article class="media content-section">
            <div class="media-body">
                <a href="{{ url_for('posts.dish_category', category_id = category.id) }}"><h4>{{ category.name }}</h4></a>
            </div>
        </article>
    {% endfor %}
    {% for page_num in categories.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if categories.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.categories', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.categories', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

appliction/application/templates/dish_categories.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Dishes in {{ category.name }} category</h1>
    {% for post in result %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post[3]) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post[2]) }}">{{ post[2] }}</a>
                    <small class="text-muted">{{ post[1].strftime('%d-%m-%Y %H:%M') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post[0]) }}">{{ post[4] }}</a></h2>
                <p class="article-content">{{ post[5] }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

appliction/application/templates/dish_cuisines.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Dishes in {{ cuisine.name }} cuisine</h1>
    {% for post in result %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post[3]) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post[2]) }}">{{ post[2] }}</a>
                    <small class="text-muted">{{ post[1].strftime('%d-%m-%Y %H:%M') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post[0]) }}">{{ post[4] }}</a></h2>
                <p class="article-content">{{ post[5] }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

appliction/application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/f0d0e02e85.js" crossorigin="anonymous"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel = "stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Chef blog - {{title}}</title>
    {% else %}
        <title>Chef blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Chef Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>
                    <form method="POST" action="{{ url_for('main.search') }}" class="d-flex">
                        {{ form.hidden_tag() }}
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched"/>
                        <button class="btn btn-dark" type="submit">Search</button>
                    </form>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{ current_user.username }}</a>
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Wonderful Sidebar</h3>
                    <p class='text-muted'>The final version of product may differ.</p>
                    <ul class="list-group">
                        <a href="{{ url_for('users.favourite') }}"><li class="list-group-item list-group-item-light">Favourites</li></a>
                        <a href="{{ url_for('main.categories') }}"><li class="list-group-item list-group-item-light">Categories</li></a>
                        <a href="{{ url_for('main.cuisines') }}"><li class="list-group-item list-group-item-light">Cuisines</li></a>
                        <a href="{{ url_for('main.ingredients') }}"><li class="list-group-item list-group-item-light">Ingredients</li></a>
                    </ul>
                </div>
            </div>
        </div>
    </main>

     <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

appliction/application/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y %H:%M') }}</small>
                <div>
                    {% if post.author == current_user or current_user.role == 'admin' %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Edit</a>
                            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                        </div>
                    {% endif %}
                    {{ post.like|length }}
                    {% if current_user in post.like|map(attribute="author")|list %}
                        <a href="/like-post/{{ post.id }}"><i class="fa-solid fa-thumbs-up"></i></a>
                    {% else %}
                        <a href="/like-post/{{ post.id }}"><i class="fa-regular fa-thumbs-up"></i></a>
                    {% endif %}
                </div>
            </div>
            <h1 class="article-title">{{ post.title }}</h1>
            <p class="lead">Origins:</p>
            {% for origin in cuisines %}
                {% for cuisine in post.cuisines %}
                    {% if origin.id == cuisine.id %}
                        <p>{{ origin.name }}</p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <p class="lead">Categories:</p>
            {% for category in categories %}
                {% for diet in post.categories %}
                    {% if category.id == diet.id %}
                        <p>{{ category.name }}</p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <p class="lead">Ingredients:</p>
            {% for ingredient in post.ingredients %}
                {% for product in amount %}
                    {% if ingredient.id == product[1] %}
                        <p>{{ ingredient.name }}: {{ product[2] }} </p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            <p class="lead">Macronutrients: </p>
            <p>Calories: {{ post.calories }}</p>
            <p>Proteins: {{ post.proteins }}</p>
            <p>Lipids: {{ post.lipids }}</p>
            <p>Carbohydrates: {{ post.carbohydrates }}</p>
            <hr class="hr"/>
            <p style="font-size:20px;" class="article-content">{{ post.content }}</p>

        </div>
    </article>
    <div class="content-section ms-5">
        <div class="card-body">
            <div class="card-text"></div>
            <h3>Leave a comment!</h3>
            <br/>
            <div class="collapse" id="comments-{{ post.id }}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{ post.id }}">
                        {% for comment in post.comments %}
                        <div class="content-section">
                            <div class="f-flex justify-content-between align-items-center">
                                <a href="{{ url_for('users.user_posts', username=comment.author.username) }}">{{ comment.author.username }}</a>: {{ comment.text }}
                                <small class="text-muted d-flex justify-content-end">{{ comment.timestamp.strftime('%d-%m-%Y %H:%M') }}</small>
                                {% if current_user == comment.author or current_user == post.author or current_user.role == 'admin' %}
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a>
                                                </li>
                                          </ul>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <p class="card-text">
                {% if post.comments|length > 0 %}
                    <a data-bs-toggle="collapse" href="#comments-{{ post.id }}" role="button">
                        <small>View/Hide {{ post.comments|length }} Comments</small>
                    </a>
                {% else %}
                    <small class="text-muted">Become the first one to review!</small>
                {% endif %}
            </p>
            <form class="input-group" method="POST" action="/create-comment/{{ post.id }}">
                <input type="text" id="text" name="text" class="form-control" placeholder="Have something to say?"/>
                <button type="submit" class="btn btn-outline-primary">Submit</button>
            </form>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>You won't be able to cancel this action.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="SUBMIT" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}